#!/usr/bin/env python3

from datetime import date
from textwrap import dedent
import sys

from contextlib import contextmanager

import psycopg2
from psycopg2 import extras

class ExpenseData():

    @contextmanager
    def _database_connect(self):
        connection = psycopg2.connect(dbname='expenses')
        try:
            with connection:
                 yield connection
        finally:
            connection.close()

    def list_expenses(self):
        # connection = psycopg2.connect(dbname='expenses')
        # try:
        #     with connection:
        with self._database_connect() as connection:
            with connection.cursor(cursor_factory=extras.DictCursor) as cursor:
                cursor.execute("""SELECT * FROM expenses 
                                    ORDER BY created_on""")
                expenses = cursor.fetchall()

        for expense in expenses:
            columns = [
                str(expense["id"]).rjust(3),
                str(expense["created_on"]),
                str(expense["amount"]).rjust(12),
                str(expense["memo"])
            ]
            print(" | ".join(columns))

    def add_expense(self, amount, memo):
        with self._database_connect() as connection:
            with connection.cursor() as cursor:
                cursor.execute("""INSERT INTO expenses (amount, memo, created_on) 
                                        VALUES (%s, %s, %s)
                                """, 
                                (amount, memo, date.today())
                            ) 

class CLI():
    def __init__(self):
        self.application = ExpenseData()
    # create an instance object of ExpenseData (inside init)

    def display_help(self): 
    # transform into an instance method 
        print(dedent("""
            An expense recording system

            Commands:

            add AMOUNT MEMO [DATE] - record a new expense
            clear - delete all expenses
            list - list all expenses
            delete NUMBER - remove expense with id NUMBER
            search QUERY - list expenses with a matching memo field
        """).strip("\n"))

    def run(self, arguments):
        if not arguments:
            command = None
        else:
            command = arguments.pop(0)

        match command:
            case "add":
                if len(arguments) < 2:
                    print("You must provide an amount and memo.")
                    return 
                amount, memo = arguments
                self.application.add_expense(amount, memo)
            case "list":
                self.application.list_expenses()
            case _:
                self.display_help()

if __name__ == "__main__":
    cli = CLI() #instance object of class CLI()
    cli.run(sys.argv[1:]) # instance method run()